"""Export the 169x169 heads-up all-in equity matrix to JS for the
'equity vs opponent range' chart. M[i][j] = hand i's equity vs hand j.
"""
from __future__ import annotations

import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
OUT = os.path.join(ROOT, "web", "charts", "strength", "equity.js")


def main():
    from pushfold.cards import HAND_CLASSES, COMBO_WEIGHTS
    from pushfold.equity import load_or_build_hu_matrix

    M = load_or_build_hu_matrix(iters=10000)
    data = {
        "hands": HAND_CLASSES,
        "w": COMBO_WEIGHTS,
        "M": [[round(float(M[i][j]), 4) for j in range(169)] for i in range(169)],
    }
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("// Auto-generated by scripts/export_equity_js.py — heads-up all-in equity matrix.\n")
        f.write("window.EQ = ")
        json.dump(data, f, separators=(",", ":"))
        f.write(";\n")
    print(f"wrote {OUT} ({os.path.getsize(OUT):,} bytes)")


if __name__ == "__main__":
    main()
