"""Compute P(hand is the strongest at showdown) vs N random opponents, for
N = 1..5, for all 169 starting hands. Written to web/charts/strength/data.js.

In a 6-handed table, if everyone ahead of you folds, your opponents are the
players still behind you — so seat maps to opponent count:
  UTG->5  MP->4  CO->3  BTN->2  SB->1.

Ties split (values are pot-equity = probability of being best, sharing ties).
"""
from __future__ import annotations

import os
import random
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

import eval7  # noqa: E402
from pushfold.cards import HAND_CLASSES, class_combos  # noqa: E402

OUT = os.path.join(ROOT, "web", "charts", "strength", "data.js")
FULL_DECK = [eval7.Card(r + s) for r in "23456789TJQKA" for s in "cdhs"]
ITERS = 25000
MAX_OPP = 5         # compute vs 1..5 opponents in one pass


def prob_strongest(i: int, iters: int, rng: random.Random):
    """Return [P(best vs 1 opp), ..., P(best vs MAX_OPP opps)] for class i."""
    combos = class_combos(HAND_CLASSES[i])
    share = [0.0] * MAX_OPP
    for _ in range(iters):
        ci = rng.choice(combos)
        deck = [c for c in FULL_DECK if c != ci[0] and c != ci[1]]
        draw = rng.sample(deck, MAX_OPP * 2 + 5)        # 5 opp hands + 5 board
        board = draw[MAX_OPP * 2:]
        hs = eval7.evaluate([ci[0], ci[1], *board])
        ties, beaten = 1, False
        for k in range(MAX_OPP):                         # add opponents one at a time
            ov = eval7.evaluate([draw[2 * k], draw[2 * k + 1], *board])
            if ov > hs:
                beaten = True
            elif ov == hs:
                ties += 1
            if not beaten:                               # share vs first (k+1) opponents
                share[k] += 1.0 / ties
    return [s / iters for s in share]


def _worker(args):
    idxs, seed = args
    rng = random.Random(seed)
    return {i: prob_strongest(i, ITERS, rng) for i in idxs}


def main():
    import json
    import multiprocessing as mp

    procs = max(1, (os.cpu_count() or 2) - 1)
    chunks = [list(range(169))[k::procs] for k in range(procs)]
    args = [(chunk, 4242 + k) for k, chunk in enumerate(chunks)]

    print(f"computing P(strongest) vs 1..{MAX_OPP} opps for 169 hands, {ITERS} sims each, {procs} procs...")
    probs = {}
    with mp.Pool(procs) as pool:
        for part in pool.imap_unordered(_worker, args):
            probs.update(part)

    # seat -> opponent count (6-handed, everyone ahead folded)
    seats = [("UTG", 5), ("MP", 4), ("CO", 3), ("BTN", 2), ("SB", 1)]
    by_seat = {}
    for name, n_opp in seats:
        by_seat[name] = {HAND_CLASSES[i]: round(probs[i][n_opp - 1], 4) for i in range(169)}

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    payload = {
        "meta": {"players": 6, "metric": "P(best hand at showdown), ties split, assuming all ahead folded",
                 "seats": [{"name": n, "opponents": o} for n, o in seats]},
        "bySeat": by_seat,
    }
    with open(OUT, "w") as f:
        f.write("// Auto-generated by scripts/strength_chart.py\n")
        f.write("window.STRENGTH = ")
        json.dump(payload, f, separators=(",", ":"))
        f.write(";\n")

    print(f"wrote {OUT}")
    for name, n_opp in seats:
        d = by_seat[name]
        print(f"  {name} (vs {n_opp}): AA {d['AA']:.1%}  72o {d['72o']:.1%}")


if __name__ == "__main__":
    main()
